### ISSUE TITLE
VMHealthDefinition has wrong username/password field

### ISSUE THREAD

**Issue by sciack** [PaesslerAG/JMXMiniProbe#2]
VMHealthDefinition define username & password as:
``rmi_username``
``rmi_password``
but are read as ``username`` and ``password``
I built a patch on VMHealthSensor and VMHealthDefintion in order to publish the right fields and read both, for some reason PRTG on my environment still send the old definition even dropping and recreate the sensor.
[rmi_username_patch.txt](https://github.com/PaesslerAG/JMXMiniProbe/files/601981/rmi_username_patch.txt)

**Comment by martinorob** [comment]
Hi @JRAndreassen , please may you compile a new  pre-built WAR with the commit 8ada0de68bcb5f9c60c5952920b04023a4285141

(that solve this issue)
?

Thanks
